/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
  aws_project_region: 'us-east-1',
  aws_cognito_identity_pool_id: 'us-east-1:8b6d663e-9d68-418e-bf83-f10bab779fe4',
  aws_cognito_region: 'us-east-1',
  aws_user_pools_id: 'us-east-1_lEEuqWL44',
  aws_user_pools_web_client_id: '8qhlto7ft3gc838sgv2piph5j',
  oauth: {},
  aws_appsync_graphqlEndpoint: 'https://faobz4m4e5ghnnlrnopicml55y.appsync-api.us-east-1.amazonaws.com/graphql',
  aws_appsync_region: 'us-east-1',
  aws_appsync_authenticationType: 'AMAZON_COGNITO_USER_POOLS',
  aws_user_files_s3_bucket: '5g-enterprise-assets192132-dev',
  aws_user_files_s3_bucket_region: 'us-east-1'
}

export default awsmobile
